CREATE TYPE "token_type" AS ENUM (
  'BEARER'
);

CREATE TABLE "projects" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "user_id" BIGINT NOT NULL
);

CREATE TABLE "activities" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "predecessors" TEXT,
  "days_duration" INT NOT NULL,
  "close_start" INT DEFAULT null,
  "distant_start" INT DEFAULT null,
  "close_finish" INT DEFAULT null,
  "distant_finish" INT DEFAULT null,
  "slack" INT DEFAULT null,
  "project_id" BIGINT NOT NULL
);

CREATE TABLE "calculations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "critical_path" TEXT NOT NULL,
  "estimated_duration" INT NOT NULL,
  "project_id" BIGINT NOT NULL
);

CREATE TABLE "tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token" TEXT UNIQUE NOT NULL,
  "token_type" token_type NOT NULL,
  "is_revoked" BOOL NOT NULL,
  "is_expired" BOOL NOT NULL,
  "user_id" BIGINT NOT NULL
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" VARCHAR(255) NOT NULL,
  "username" VARCHAR(30) NOT NULL,
  "email" VARCHAR(254) UNIQUE NOT NULL,
  "password" TEXT NOT NULL,
  "date_of_birth" DATE NOT NULL
);

COMMENT ON COLUMN "activities"."label" IS 'The format starts with A-Z, then AA-ZZ, AAA-ZZZ, etc.';

COMMENT ON COLUMN "activities"."predecessors" IS 'The format is comma-separated, for example: "A,B,C,D"';

COMMENT ON COLUMN "activities"."close_start" IS 'The value corresponds to days';

COMMENT ON COLUMN "activities"."distant_start" IS 'The value corresponds to days';

COMMENT ON COLUMN "activities"."close_finish" IS 'The value corresponds to days';

COMMENT ON COLUMN "activities"."distant_finish" IS 'The value corresponds to days';

COMMENT ON COLUMN "activities"."slack" IS 'The value corresponds to days';

COMMENT ON COLUMN "calculations"."critical_path" IS 'The format is hyphen-separated, for example: "L-M-N-O-P"';

COMMENT ON COLUMN "calculations"."estimated_duration" IS 'The value corresponds to days';

ALTER TABLE "activities" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "calculations" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "projects" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
